$ANSIBLE_VAULT;1.1;AES256
39363537356166313339313761363436656237323733666634616465393835323831623265336634
6161663030636664326539336634326361616632306334330a336433336235316566666165623661
65353664613436636466363366646266666661336366346531363433316361643062383862363564
6563626234343130350a313563613261386633336161383735353133313861623535636139333537
64343964343238373463303839646539373336386630313231643033386136383739383938636539
31393864336362656130306430666465326130336333306564393936313134313938663031313939
62656236323133623761623030636337393437663731633439376633613863386261316264343934
31646430613336383962373930366661373063643161633137653734386634626336396165633264
35653034396662653665663461653534613263313761323836633830663936616164313639363139
34396639623633326638393638333766306164626338376138373065393137393863386165316632
61343439343766373933383066333762666130636431643038326464363038306630666233336337
36383438373830323139623837666334663164643234653261376337346664623236653063373662
30653166333038636634646635303836353738316434626162303264623033653234343434383233
62393335623965303137383930326637396437346631616335663538313835386636373865373964
38313136346563663732313534643064386164396163653334306466353932636130386531336262
35326662386564653265653965333066656337656234363163373466633532636432626533333433
30396636313966383539626535326339313164386332633131626334363335633337366238353531
38316438393534336661623461663962366335373232373665653732626230316139643236623166
65656538373533346635363662303838323632643631333061313839306535376264633831313233
62356132663063653937
